### ISSUE TITLE
White and pial vertices/faces not in correspondence

### ISSUE THREAD

**Issue by chrisadamsonmcri** [MIRTK/Deformable#10]
Using the default recon-neonatal-cortex script with default options except for -ensure-pial-is-outside-white-surface and the white and pial surfaces are not in correspondence. The surfaces are in the correct locations but face configuration differs between white and pial. This happens both in the dual-hemisphere and split surfaces. Any thoughts? Thank you in advance.

**Comment by schuhschuh** [comment]
Hi @chrisadamsonmcri, sorry for the very late reply. Have you managed to resolve the issue? There should indeed not be any difference between number of surface nodes. The pial surface is obtained by deforming the white matter surface without change in topology unless remeshing is enabled. It would be worthwhile to check if remeshing is indeed disabled for your setup.

See also [docstring or recon_pial_surface](https://github.com/MIRTK/Deformable/blob/ad6e010cc43fe1f5567f2c6a92bf2dda94db271e/lib/python/mirtk/deformable/neonatal_cortex.py#L1598).

You could also run the surface reconstruction in debug mode and check the intermediate output files, in particular the initial surface mesh created by the `-ensure-pial-is-outside-white-surface` (cf. also code [here](https://github.com/MIRTK/Deformable/blob/ad6e010cc43fe1f5567f2c6a92bf2dda94db271e/lib/python/mirtk/deformable/neonatal_cortex.py#L1677)).

**Comment by chrisadamsonmcri** [comment]
Hi,
So to clarify, what happens is that the white and pial surfaces do have the same number of vertices and have correspondence. However, the ordering of the vertices changes so they don't correspond to each other by their indices. To work around this I turn on all the debugging and I made a python script that finds matching vertices when their ordering changes. So this tracks the vertices from the final pial surfaces back to the white surfaces. I then reorder the pial vertices so that they have the same ordering as the white surfaces.
There are no PointData arrays that allow you to track back the vertex order in the vtp files. It would be good if the software did this so that the debug files would not need to be stored.

**Comment by schuhschuh** [comment]
That the order of points in the `vtkPoints` list changes is unexpected if no remeshing takes place. Without remeshing, only the point coordinates should be update during explicit surface evolution, and hence the point indices remain the same. I am running `recon-neonatal-cortex` on some dHCP data currently and can check if I observe the same issue.

**Comment by schuhschuh** [comment]
@chrisadamsonmcri When you re-established correspondences, did you maybe notice a fixed offset between white and pial surface indices? I am wondering if this may be due to [this line](https://github.com/MIRTK/Deformable/blob/ad6e010cc43fe1f5567f2c6a92bf2dda94db271e/lib/python/mirtk/deformable/neonatal_cortex.py#L1738), where initial white matter surface and brainstem plus cerebellum surfaces are appended into a single `.vtp` file. After the pial surface evolution, the two are split again [here](https://github.com/MIRTK/Deformable/blob/ad6e010cc43fe1f5567f2c6a92bf2dda94db271e/lib/python/mirtk/deformable/neonatal_cortex.py#L1867).

The use of BS+CB meshes could be disabled by setting both `bs_cb_mesh_1` and `bs_cb_mesh_2` to `None` [here](https://github.com/MIRTK/Deformable/blob/ad6e010cc43fe1f5567f2c6a92bf2dda94db271e/tools/recon-neonatal-cortex.py#L459).

**Comment by chrisadamsonmcri** [comment]
Hi Andreas,
I'm sorry it has taken a while to get back to you. I have written a "backtracking" script that finds corresponding vertices in the sequence pial->pial-6->pial-5->pial-4->pial-3->white->white-lh/rh. It works for the vast majority of cases. it would just be better to do that in the c++ code then I can delete the intermediate outputs.

I'm using the -ensure-pial-is-outside-white-surface option. At the moment I'm struggling to fix cases where the pial-5 surface contains collisions after that initial normal deformation. I think this is being caused by shocks forming at highly curved gyri and opposite banks crashing into each other.

**Comment by chrisadamsonmcri** [comment]
I think I have narrowed this error down. I'm using the -ensure-pial-is-outside-white-surface option. The problem vertices seem to be vertices that don't move during the initial pial-1.vtp -> pial-2.vtp normal "push" step. They get merged out when the original white is added back. Thankfully these vertices tend to detect errors in the original white matter surface. So I think this is what is happening. Upon fixing the segmentation the error doesn't occur.
