### ISSUE TITLE
Error compiling Deformable module without TBB

### ISSUE THREAD

**Issue by NeuroImagingWorld** [MIRTK/Deformable#6]
I am trying to use "calculate-surface-spectrum" which is requiring that "Numerics module was built with ARPACK and UMFPACK". (on Ununtu 14.04)

However when trying to build and install mirtk with above options, running into below issues.

make[2]: *** [Packages/Deformable/src/CMakeFiles/LibDeformable.dir/ImageEdgeDistance.cc.o] Error 1
make[1]: *** [Packages/Deformable/src/CMakeFiles/LibDeformable.dir/all] Error 2

.....
request for member ‘insert’ in ‘extrema’, which is of non-class type ‘mirtk::ImageEdgeDistanceUtils::ComputeDistances::Extrema {aka int}’
                     r = extrema.insert(r, mid);
......

ImageEdgeDistance.cc:1355:28: note:   mismatched types ‘_Tp [_Nm]’ and ‘int’
     for (auto &&extremum : extrema) {

Can you please assist.

**Comment by schuhschuh** [comment]
Do you think there are some relevant error messages missing from your report? I could imagine one scenario where the compiler fails to resolve the typedef of Extrema (see [this line](https://github.com/MIRTK/Deformable/blob/c43074a0f4a434ef07d7251ec88d6bd73b56799f/src/ImageEdgeDistance.cc#L729)) and thus consider this type to be simply the default `int`. It's when you compile the Deformable module without TBB... something I have to fix in the code.

In the meantime, try setting `WITH_TBB=ON` in CMake (it's an advanced option). This will then enable multi-threaded execution and generally speed up things.

May I ask what you would like to use `calculate-surface-spectrum` for ? Thing is that this tool is not yet stable and only partially implemented. For example, option `-target` to match the eigenmodes of another surface is not implemented (specifically the Hungarian algorithm). Also, the computation of joined eigenmodes as used for the "diffeomorphic spectral matching" is not available yet either (there is a [coherent point drift (CPD) library for C++](https://github.com/gadomski/cpd) now available that could be used for this). At the moment, you can only use it to compute the eigenmodes of a single surface mesh.

**Comment by schuhschuh** [comment]
Building this module without TBB should now be fixed in the master branch of MIRTK. However, I recommend building the MIRTK with multi-threading enabled if single-threaded execution on a cluster system is not required, and even then `-threads 1` option can be used.

See https://github.com/BioMedIA/MIRTK/commit/3fc1668c66b91397005f8d69fdae84cd55e13ba8.

**Comment by NeuroImagingWorld** [comment]
Hi Andreas,

  Thank you for the quick response. We have a bunch of whole brain cortical
surfaces (not hemisphere based) that we need nonlinearly aligned to get
quick correspondence out of the box. "Diffeomorphic Spectral Matching of
Cortical Surfaces" seem to be promising. We couldn't access matlab
implementation but were glad to see that it got implemented into MIRTK. I
will try with the option you suggested.

Do you suggest any other implementation that is suitable for our surface
registration that I can look at.

Appreciate your assistance.

Thanks,
Prasanna

**Comment by schuhschuh** [comment]
Hi Prasanna,

in that case I'm sorry I have to disappoint you. As noted, the current implementation cannot be used for diffeomorphic spectral matching. You can download the MATLAB code from Herve's web page at: http://profs.etsmtl.ca/hlombaert/projects.php (seems this page is missing a menu entry now).

Best,
Andreas

**Comment by NeuroImagingWorld** [comment]
Hi Andreas,

  No problem, thank you for letting me know. Yes, I tried the matlab link
from that webpage but looks like its broken.

Thanks,
Prasanna

**Comment by schuhschuh** [comment]
Prasanna, can you send me an email to andrea.schuh@imperial.ac.uk ?

**Comment by schuhschuh** [comment]
Sorry, it's andreas.schuh@imperial.ac.uk ...
