### ISSUE TITLE
feature request: user-defined lh/rh labels in recon-neonatal-cortex.py

### ISSUE THREAD

**Issue by MrBurnst** [MIRTK/Deformable#8]
The lh / rh label definitions are hard-coded in recon-neonatal-cortex.py and could be made user-defineable like the labels are. otherwise for instance the automatic hemisphere splitting does not work with user-defined labels.

**Comment by schuhschuh** [comment]
Thanks for the suggestion. You can, however, already do this.

Set `right_hemisphere_labels` and `left_hemisphere_labels` in the config file. See [code](https://github.com/MIRTK/Deformable/blob/1996a9f7730cc51855d21c4565d9298dbee6a8f8/tools/recon-neonatal-cortex.py#L119): the hard-coded labels are only used as default values when not specified in the config file.

**Comment by schuhschuh** [comment]
Resp, labels are read [here](https://github.com/MIRTK/Deformable/blob/1996a9f7730cc51855d21c4565d9298dbee6a8f8/tools/recon-neonatal-cortex.py#L186).
