### ISSUE TITLE
Merged surface is non-closed, no. of boundaries

### ISSUE THREAD

**Issue by chrisadamsonmcri** [MIRTK/Deformable#9]
I'm having an issue with the reconstruction. I end up with a non-closed surface and all the boundary edges are on the midline where the two cerebral surfaces connect (see attached for the regions.nii.gz file with the cerebrum-1.vtp surface overlaid and the boundary edges in white dots). I'm not sure how to address this?

Thanks in advance.
![surface_boundary_edges](https://user-images.githubusercontent.com/9276757/36134665-573392ae-10da-11e8-95d2-515fcfb8f1b0.png)

**Comment by chrisadamsonmcri** [comment]
It's the VTK 6 problem. Fixed.

**Comment by schuhschuh** [comment]
Glad you found the issue and thanks for letting us know.

**Comment by chrisadamsonmcri** [comment]
This problem is now happening with VTK 8.1.0

**Comment by chrisadamsonmcri** [comment]
Join threshold had to be lowered.
